# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f37f543bc65eee7933cb2985bf762ec88099a38d865c50a0821b5012f78f612fb5ee13d33b5bd20cff28fcb09329c55581e603b13beb27d7817953ce90d0ad3a

test:
  secret_key_base: 0572234980b85b91115fe36fccff9b47823efb6742183cac28b07dc221f42fd936bf9012ff660608942ae1610e06004bf32945d27458413e372706907bd07a6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
